<Project Sdk="LibreWPF.Sdk">
  <PropertyGroup>
  	<OutputType>Library</OutputType>
	<UseWPF Condition="'$(TargetFramework)' == 'net481'">true</UseWPF>
	<LangVersion>latest</LangVersion>
	<NoWarn>$(NoWarn);CS1572;CS1573;CS1591</NoWarn>
	<AssemblyName>ICSharpCode.WpfDesign.Designer</AssemblyName>
	<Version>8.1</Version>
	<AssemblyVersion>8.1.0.0</AssemblyVersion>
	<FileVersion>8.1.0.0</FileVersion>
	<Company>ic#code</Company>
	<Copyright>2000-2021 AlphaSierraPapa for the SharpDevelop Team</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\WpfDesign.XamlDom\Project\WpfDesign.XamlDom.csproj" />
    <ProjectReference Include="..\..\WpfDesign\Project\WpfDesign.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net481'">
    <Reference Include="ReachFramework" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Images\*" />
    <Resource Include="Images\*" />
  </ItemGroup>
</Project>
