<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<OutputType>Library</OutputType>
    <TargetFrameworks>net10.0-windows;net481</TargetFrameworks>
		<DocumentationFile>..\..\bin\$(TargetFramework)\ICSharpCode.WpfDesign.XamlDom.xml</DocumentationFile>
		<OutputPath>..\..\bin\</OutputPath>
	<UseWPF>true</UseWPF>
	<LangVersion>latest</LangVersion>
	<NoWarn>$(NoWarn);CS1572;CS1573;CS1591</NoWarn>
	<AssemblyName>ICSharpCode.WpfDesign.XamlDom</AssemblyName>
	<Version>8.1</Version>
	<AssemblyVersion>8.1.0.0</AssemblyVersion>
	<FileVersion>8.1.0.0</FileVersion>
	<Company>ic#code</Company>
	<Copyright>2000-2021 AlphaSierraPapa for the SharpDevelop Team</Copyright>
  </PropertyGroup>
</Project>
